# Site settings
title: Jimrok Liu
email: jiang717@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  个人博客，记录读书、编程和其他有意思的事情。你可以引用我的Jekyll模版，但请不要转载任何内容。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jimrok.github.io" # the base hostname & protocol for your site
twitter_username: jimrokliu
github_username:  jimrok

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
input: GFM

permalink: /:year/:month/:day/:title.html